name: Pull Request 템플릿
description: PR 생성 시 작성할 내용을 안내합니다.
title: 'feat: '
labels: []
assignees: []

body:
  - type: input
    id: issue-number
    attributes:
      label: ⭐️ Issue Number
      description: 해당되는 이슈 번호가 없다면 "None"이라고 작성해주세요.
      placeholder: "#123 또는 None"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📢 Description
      description: 구현/수정한 내용을 간결하게 bullet 형식으로 작성해주세요.
      placeholder: |
        - 기능 요약
        - 문서 작업 요약
        - 코드 리팩토링 요약
    validations:
      required: true

  - type: textarea
    id: tech-concerns
    attributes:
      label: 🛠️ Technical Concerns
      description: 리뷰어나 팀원이 주의 깊게 봐야 할 기술적 포인트를 작성해주세요.
      placeholder: |
        - 로직 변경
        - DB 스키마 수정
        - 성능 이슈

  - type: textarea
    id: warnings
    attributes:
      label: ⚠️ Notice & Warning
      description: 유의사항 또는 팀원에게 공지할 항목이 있다면 작성해주세요.
      placeholder: |
        - env 설정 추가됨
        - .png 확장자만 사용 가능

  - type: checkboxes
    id: reviewers
    attributes:
      label: 🙂 To Reviewer
      description: 리뷰어가 여러 명이라면 확인 후 체크 표시를 남겨주세요.
      options:
        - label: @리뷰어1
        - label: @리뷰어2
        - label: @리뷰어3

  - type: checkboxes
    id: todo
    attributes:
      label: 📋 To Do
      description: 이 PR 안에서 완료되거나 진행 중인 항목을 기록해주세요.
      options:
        - label: [x] 완료된 항목
        - label: [ ] 진행 중이거나 남은 항목

  - type: textarea
    id: followup
    attributes:
      label: 📌 Follow-Up Task
      description: 이후에 이어서 진행할 작업을 자유롭게 정리해주세요.
      placeholder: |
        - API 문서 작성
        - 다이어그램 세분화
        - 리팩토링 예정 기능 정리
