name: feat issue template
description: 새로운 기능 개발을 위한 이슈를 생성해주세요.
title: 'Feat: 작업 제목'
labels: ['Feat']
assignees: []

body:
  - type: textarea
    id: feature-desc
    attributes:
      label: 🥸 어떤 기능인가요?
      description: 추가하려는 기능을 설명해주세요.
      placeholder: ex) 사용자가 프로필을 수정할 수 있도록 UI를 추가합니다.
    validations:
      required: true

  - type: checkboxes
    id: todo
    attributes:
      label: ✅ 작업 내용
      description: 기능 개발에 필요한 작업 목록을 체크박스로 정리해주세요.
      options:
        - label: TODO 1
        - label: TODO 2
        - label: TODO 3

  - type: input
    id: deadline
    attributes:
      label: 😇 이때까지 끝낼게요!
      description: 기능 개발 완료 예상 날짜를 작성해주세요.
      placeholder: 예: 2025-04-18
    validations:
      required: false

  - type: textarea
    id: reference
    attributes:
      label: 😵 참고할만한 자료 (선택)
      description: 참고 문서, 레퍼런스 링크가 있다면 자유롭게 작성해주세요.
      placeholder: 예: FastAPI Docs / 디자인 시안 링크 등

  - type: checkboxes
    id: confirmation
    attributes:
      label: 🙇‍♀️ 이슈 확인했어요:)
      description: 팀원에게 이슈 확인을 요청해주세요.
      options:
        - label: 팀원1
        - label: 팀원2
        - label: 팀원3
