name: refactor task
description: 기능 변경 없이 코드 품질이나 구조 개선을 위한 작업입니다.
title: 'refactor: '
labels: ['refactor']
assignees: []

body:
  - type: textarea
    id: reason
    attributes:
      label: 🧹 리팩토링 이유
      description: 왜 리팩토링이 필요한가요? 목적이나 배경을 설명해주세요.
      placeholder: ex) 코드 중복이 많고 가독성이 떨어져 유지보수가 어렵습니다.
    validations:
      required: true

  - type: checkboxes
    id: refactor-items
    attributes:
      label: 🔧 리팩토링 항목
      description: 어떤 항목을 개선할 예정인가요?
      options:
        - label: 네이밍 개선
        - label: 불필요한 코드 제거
        - label: 중복 로직 제거
        - label: 모듈 분리
        - label: 테스트 커버리지 개선

  - type: textarea
    id: side-effects
    attributes:
      label: ⚠️ 영향도 / 부작용
      description: 이 리팩토링이 시스템에 어떤 영향을 줄 수 있나요?
      placeholder: ex) 사용자 정보 처리 로직이 변경되어 DB 스키마 검토가 필요함

  - type: textarea
    id: extra-notes
    attributes:
      label: 📝 기타 참고사항
      description: 관련 문서나 참고할 내용이 있다면 작성해주세요.
      placeholder: 예: 관련 이슈 링크 / RFC 문서
